version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: financial-dashboard-postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - financial-dashboard-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: financial-dashboard-server
    restart: always
    depends_on:
      - postgres
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=5433
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PORT=${PORT:-4000}
      - NODE_ENV=production
    ports:
      - "${PORT:-4000}:4000"
    networks:
      - financial-dashboard-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: financial-dashboard-client
    restart: always
    depends_on:
      - server
    environment:
      - VITE_API_URL=/api/graphql
    ports:
      - "80:80"
    networks:
      - financial-dashboard-network

networks:
  financial-dashboard-network:
    driver: bridge

volumes:
  postgres-data:
