version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: financial-dashboard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT:-5433}:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - financial-dashboard-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: financial-dashboard-server
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=5433
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PORT=${PORT:-4000}
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${PORT:-4000}:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - financial-dashboard-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: financial-dashboard-client
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:${PORT:-4000}/api/graphql
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - financial-dashboard-network

networks:
  financial-dashboard-network:
    driver: bridge

volumes:
  postgres-data:
