FROM node:20-alpine as build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/package.json /app/yarn.lock ./

RUN yarn install --production

COPY --from=build /app/dist ./dist

EXPOSE 4000

CMD ["node", "dist/server.ts"]